(function(root) {
  'use strict';
  const G = root.DocumentScannerGeometry;
  const OPENCV_URL = 'https://docs.opencv.org/4.10.0/opencv.js';
  let cvPromise;
  function loadOpenCv(timeoutMs) {
    if (root.cv && root.cv.Mat) return Promise.resolve(root.cv);
    if (cvPromise) return cvPromise;
    cvPromise = new Promise((resolve, reject) => {
      const old = root.Module || {};
      const timer = setTimeout(() => reject(new Error('OpenCV загружается слишком долго.')), timeoutMs || 12000);
      root.Module = Object.assign({}, old, { onRuntimeInitialized: () => { clearTimeout(timer); resolve(root.cv); } });
      const script = document.createElement('script'); script.async = true; script.src = OPENCV_URL;
      script.onerror = () => { clearTimeout(timer); reject(new Error('Не удалось загрузить обработку документов.')); };
      document.head.appendChild(script);
    }).catch(error => { cvPromise = null; throw error; });
    return cvPromise;
  }
  function canvasBlob(canvas, quality) { return new Promise((resolve, reject) => canvas.toBlob(blob => blob ? resolve(blob) : reject(new Error('Не удалось сохранить скан.')), 'image/jpeg', quality)); }
  function loadImage(file) { return new Promise((resolve, reject) => { const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => { URL.revokeObjectURL(url); resolve(image); }; image.onerror = () => { URL.revokeObjectURL(url); reject(new Error('Не удалось открыть изображение.')); }; image.src = url; }); }
  function sourceCanvas(image, maxSide) { const scale = Math.min(1, maxSide / Math.max(image.naturalWidth || image.width, image.naturalHeight || image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.max(2, Math.round((image.naturalWidth || image.width) * scale)); canvas.height = Math.max(2, Math.round((image.naturalHeight || image.height) * scale)); canvas.getContext('2d', { alpha:false }).drawImage(image, 0, 0, canvas.width, canvas.height); return canvas; }
  function quality(canvas, areaRatio, detected) { const data = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data; let sum = 0, white = 0; for (let i = 0; i < data.length; i += 16) { const y = .2126 * data[i] + .7152 * data[i + 1] + .0722 * data[i + 2]; sum += y; if (y > 245) white += 1; } const count = Math.ceil(data.length / 16); const brightness = sum / count; const warnings = []; if (!detected) warnings.push('Границы документа не найдены: используется исходное фото.'); if (brightness < 45) warnings.push('Снимок тёмный — проверь читаемость.'); if (white / count > .45) warnings.push('Есть сильный пересвет.'); if (Math.max(canvas.width, canvas.height) < 900) warnings.push('Разрешение скана небольшое.'); return { brightnessScore: Math.round(brightness), overexposedRatio: Number((white / count).toFixed(2)), documentAreaRatio: Number((areaRatio || 0).toFixed(2)), warnings }; }
  function detect(canvas, cv) { let src, small, gray, blur, edges, contours, hierarchy; try { src = cv.imread(canvas); const scale = Math.min(1, 1100 / Math.max(src.cols, src.rows)); small = new cv.Mat(); cv.resize(src, small, new cv.Size(Math.round(src.cols * scale), Math.round(src.rows * scale))); gray = new cv.Mat(); blur = new cv.Mat(); edges = new cv.Mat(); cv.cvtColor(small, gray, cv.COLOR_RGBA2GRAY); cv.GaussianBlur(gray, blur, new cv.Size(5,5), 0); cv.Canny(blur, edges, 60, 160); contours = new cv.MatVector(); hierarchy = new cv.Mat(); cv.findContours(edges, contours, hierarchy, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE); let best = null, bestArea = 0; const frame = small.cols * small.rows; for (let i=0;i<contours.size();i+=1) { const contour=contours.get(i), approx=new cv.Mat(); cv.approxPolyDP(contour, approx, .02*cv.arcLength(contour,true), true); const area=cv.contourArea(approx); if (approx.rows===4 && cv.isContourConvex(approx) && area>frame*.15 && area<frame*.97 && area>bestArea) { const points=[]; for(let j=0;j<4;j+=1){const p=approx.intPtr(j,0);points.push({x:p[0]/scale,y:p[1]/scale});} const corners=G.sortCorners(points); if(G.isConvex(corners)){best=corners;bestArea=area;} } approx.delete(); contour.delete(); } return best ? { corners:best, areaRatio:bestArea/frame } : null; } finally { [src,small,gray,blur,edges,contours,hierarchy].forEach(mat=>{if(mat)mat.delete();}); } }
  function transform(canvas, corners, cv, maxLongSide) { const size=G.outputSize(corners,maxLongSide); const src=cv.imread(canvas), dst=new cv.Mat(), srcPts=cv.matFromArray(4,1,cv.CV_32FC2,[corners.topLeft.x,corners.topLeft.y,corners.topRight.x,corners.topRight.y,corners.bottomRight.x,corners.bottomRight.y,corners.bottomLeft.x,corners.bottomLeft.y]), dstPts=cv.matFromArray(4,1,cv.CV_32FC2,[0,0,size.width-1,0,size.width-1,size.height-1,0,size.height-1]), matrix=cv.getPerspectiveTransform(srcPts,dstPts), out=document.createElement('canvas'); try { cv.warpPerspective(src,dst,matrix,new cv.Size(size.width,size.height),cv.INTER_LINEAR,cv.BORDER_REPLICATE); out.width=size.width;out.height=size.height;cv.imshow(out,dst);return out;} finally {[src,dst,srcPts,dstPts,matrix].forEach(mat=>mat.delete());} }
  function filtered(base, filter) { const out=document.createElement('canvas');out.width=base.width;out.height=base.height;const ctx=out.getContext('2d',{alpha:false});ctx.drawImage(base,0,0);if(filter==='original')return out;const image=ctx.getImageData(0,0,out.width,out.height), d=image.data;for(let i=0;i<d.length;i+=4){const l=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];if(filter==='bw'){const v=l>158?255:0;d[i]=d[i+1]=d[i+2]=v;}else{const v=Math.max(0,Math.min(255,(l-128)*1.25+138));d[i]=Math.min(255,v*1.03);d[i+1]=v;d[i+2]=Math.max(0,v*.96);}}ctx.putImageData(image,0,0);return out; }
  function openUi(base, meta, labels) { return new Promise(resolve => { let filter='document', active=filtered(base,filter); const overlay=document.createElement('div');overlay.className='ds-overlay';overlay.innerHTML='<div class="ds-card" role="dialog" aria-modal="true"><h2>'+ (labels.title||'Проверь скан') +'</h2><div class="ds-status">Границы и перспектива обработаны локально.</div><img class="ds-preview"><div class="ds-filters"><button data-filter="original">Оригинал</button><button class="active" data-filter="document">Документ</button><button data-filter="bw">Ч/Б</button></div><div class="ds-warning"></div><div class="ds-actions"><button class="danger" data-action="cancel">Отмена</button><button data-action="original">Использовать оригинал</button><button class="primary" data-action="confirm">'+(labels.confirm||'Использовать')+'</button></div></div>'; document.body.appendChild(overlay); const preview=overlay.querySelector('.ds-preview'), warning=overlay.querySelector('.ds-warning'); preview.src=active.toDataURL('image/jpeg',.88); warning.textContent=meta.quality.warnings.join(' '); overlay.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;active=filtered(base,filter);preview.src=active.toDataURL('image/jpeg',.88);overlay.querySelectorAll('[data-filter]').forEach(item=>item.classList.toggle('active',item===button));}); const finish=async usedOriginal=>{overlay.remove();const canvas=usedOriginal?meta.original:active;resolve({confirmed:true,canvas,blob:await canvasBlob(canvas,.9),filter:usedOriginal?'original':filter,corners:meta.corners,documentDetected:meta.documentDetected,usedOriginal,quality:meta.quality,width:canvas.width,height:canvas.height});};overlay.querySelector('[data-action="confirm"]').onclick=()=>finish(false);overlay.querySelector('[data-action="original"]').onclick=()=>finish(true);overlay.querySelector('[data-action="cancel"]').onclick=()=>{overlay.remove();resolve({confirmed:false});}; }); }
  class DocumentScanner { constructor(options){this.options=Object.assign({maxLongSide:2400,allowOriginal:true},options||{});} async process(file, labels){if(!file||!String(file.type||'').startsWith('image/'))throw new Error('Выбери изображение JPG или PNG.');const image=await loadImage(file),original=sourceCanvas(image,this.options.maxLongSide),meta={original,corners:null,documentDetected:false,quality:null};try{const cv=await loadOpenCv();const found=detect(original,cv);if(found){meta.corners=found.corners;meta.documentDetected=true;meta.areaRatio=found.areaRatio;meta.base=transform(original,found.corners,cv,this.options.maxLongSide);}else meta.base=original;}catch(error){console.warn('Document scanner fallback:',error);meta.base=original;}meta.quality=quality(meta.base,meta.areaRatio,meta.documentDetected);return openUi(meta.base,meta,labels||{});} }
  root.DocumentScanner = DocumentScanner;
})(window);
