const assert = require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path'); const test=require('node:test');
const b=fs.readFileSync(path.join(__dirname,'../../apps-script/stock/production/Code.gs'),'utf8'); const s=b.slice(b.indexOf('// ==== TATOOINE RIDES START ===='),b.indexOf('// ==== TATOOINE RIDES END ====')); const optimize=new Function(`${s}; return optimizeTatooineRideMatrix_;`)();
function input(names, times){const participants=names.map(x=>({employeeId:x,employeeName:x,pointId:'employee_'+x}));const edges=[];names.forEach((a,i)=>{edges.push({fromId:'origin',toId:'employee_'+a,durationSeconds:times[0][i],distanceMeters:times[0][i]*10,status:'ok'});names.forEach((c,j)=>{if(i!==j)edges.push({fromId:'employee_'+a,toId:'employee_'+c,durationSeconds:times[i+1][j],distanceMeters:times[i+1][j]*10,status:'ok'});});});return {participants,matrix:{edges}};}
test('one employee becomes one car with zero detour',()=>{const r=optimize(input(['A'],[[600],[0]]));assert.equal(r.carCount,1);assert.equal(r.cars[0].passengers[0].extraDurationSeconds,0);});
test('chooses the better directed dropoff order for two employees',()=>{const r=optimize(input(['A','B'],[[600,800],[0,120],[700,0]]));assert.deepEqual(r.cars[0].dropoffOrder,['employee_A','employee_B']);});
test('unreachable direct route is unresolved and never assigned',()=>{const x=input(['A'],[[600],[0]]);x.matrix.edges[0].status='unreachable';const r=optimize(x);assert.equal(r.carCount,0);assert.equal(r.unresolvedParticipants.length,1);});
test('capacity, uniqueness and determinism invariants hold',()=>{const x=input(['A','B','C','D'],[[600,620,640,660],[0,60,80,100],[60,0,60,80],[80,60,0,60],[100,80,60,0]]);const a=optimize(x),b=optimize(x);const ids=a.cars.flatMap(c=>c.passengers.map(p=>p.employeeId));assert.deepEqual(a.cars,b.cars);assert.equal(new Set(ids).size,4);assert.ok(a.cars.every(c=>c.passengerCount<=3));});

function two(directA, directB, ab, ba) { return input(['A','B'], [[directA,directB],[0,ab],[ba,0]]); }
test('19 and exactly 20 minutes are inclusive when ratio is within 40 percent',()=>{for(const extra of [1140,1200]){const r=optimize(two(3600,3600,extra,extra));assert.equal(r.carCount,1);assert.equal(r.cars[0].passengerCount,2);assert.equal(r.cars[0].maxExtraDurationSeconds,extra);}});
test('21 minutes and a 75 percent detour are rejected despite available direct routes',()=>{assert.equal(optimize(two(3600,3600,1260,1260)).carCount,2);assert.equal(optimize(two(1200,1200,900,900)).carCount,2);});
test('40 percent ratio is allowed and 41 percent is rejected',()=>{assert.equal(optimize(two(3000,3000,1200,1200)).carCount,1);assert.equal(optimize(two(3000,3000,1230,1230)).carCount,2);});
test('three-passenger permutations choose the only best order',()=>{const x=input(['A','B','C'],[[1200,1000,1100],[0,900,900],[900,0,60],[60,900,0]]);const r=optimize(x);assert.deepEqual(r.cars[0].dropoffOrder,['employee_B','employee_C','employee_A']);});
test('unreachable permutation is skipped while a valid alternative is selected',()=>{const x=input(['A','B'],[[1200,1000],[0,NaN],[60,0]]);x.matrix.edges.find(e=>e.fromId==='employee_A'&&e.toId==='employee_B').status='unreachable';const r=optimize(x);assert.deepEqual(r.cars[0].dropoffOrder,['employee_B','employee_A']);});
test('exact set partitioning rejects locally attractive ABC plus DE for globally better AB plus CDE',()=>{const names=['A','B','C','D','E'];const x=input(names,[[5000,5000,1000,5000,5000],[0,10,3000,3000,3000],[10,0,10,3000,3000],[3000,3000,0,3000,10],[3000,3000,3000,0,1000],[3000,3000,3000,10,0]]);const r=optimize(x);const sets=r.cars.map(c=>c.passengers.map(p=>p.employeeId).sort().join('')).sort();assert.deepEqual(sets,['AB','CDE']);assert.equal(sets.includes('ABC'),false);});
test('benchmark inputs are deterministic and heuristic preserves constraints',()=>{for(const n of [10,20,30]){const names=Array.from({length:n},(_,i)=>'E'+i);const times=[names.map((_,i)=>3600+i*10)];for(let i=0;i<n;i++)times.push(names.map((_,j)=>i===j?0:60+Math.abs(i-j)*10));const r=optimize(input(names,times));assert.equal(r.optimizationMode,n<=18?'exact':'heuristic');assert.ok(r.cars.every(c=>c.passengerCount<=3));const ids=r.cars.flatMap(c=>c.passengers.map(p=>p.employeeId));assert.equal(new Set(ids).size,n);assert.ok(r.cars.flatMap(c=>c.passengers).every(p=>p.extraDurationSeconds<=1200&&p.extraRatio<=.4));console.log('benchmark',n,r.optimizationMode,r.summary.candidateGroupCount,r.summary.optimizationDurationMs,r.carCount);}});
test('optimization persistence has config snapshot, stale state and server-side permissions',()=>{assert.match(b,/maxExtraMinutes:TATOOINE_RIDE_OPTIMIZER_CONFIG\.maxExtraMinutes/);assert.match(b,/function getTatooineRideOptimization_/);assert.match(b,/function optimizeTatooineRide_/);const start=b.indexOf('function optimizeTatooineRide_');assert.match(b.slice(start,start+500),/requireTatooinePermission_\(auth,'rides\.optimize'\)/);assert.match(b,/current\.isCurrent===false/);});
